name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest
    environment:
      name: testing  # Shows up under Deployments tab

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Start the deployment (important: sets deployment_id)
      - name: Create Deployment
        id: deployment
        uses: bobheadxi/deployments@v1
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: testing

      # Deploy files
      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          ARGS: "-avz --delete"
          EXCLUDE: ".git/, .github/, .gitignore, README.md"

      # Setup Apache if needed
      - name: Setup Apache (only run once)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_DNS }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            if [ ! -f /var/www/html/.apache_installed ]; then
              sudo apt-get -y update
              sudo apt-get install -y apache2
              sudo systemctl start apache2
              sudo systemctl enable apache2
              sudo touch /var/www/html/.apache_installed
            fi
            if [ "${{ secrets.TARGET_DIR }}" != "/var/www/html" ]; then
              sudo rsync -av ${{ secrets.TARGET_DIR }}/ /var/www/html/
            fi

      # ✅ Mark success
      - name: Mark Deployment Success
        if: success()
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          env: testing
          status: success
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}

      # ❌ Mark failure if rsync or other steps fail
      - name: Mark Deployment Failed
        if: failure()
        uses: bobheadxi/deployments@v1
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          env: testing
          status: failure
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
